CREATE OR REPLACE TRIGGER ANVIL_TRACE
AFTER LOGON ON DATABASE
BEGIN
    IF ( 
		SYS_CONTEXT('USERENV','SESSION_USER') = '...' 
		AND 
		SYS_CONTEXT ('USERENV', 'MODULE') <> '...'
		and
		SYS_CONTEXT ('USERENV', 'HOST') = '...'
		)
  THEN
    EXECUTE IMMEDIATE 'ALTER SESSION SET TIMED_STATISTICS = TRUE';
	EXECUTE IMMEDIATE 'ALTER SESSION SET STATISTICS_LEVEL=ALL';
    EXECUTE IMMEDIATE 'ALTER SESSION SET MAX_DUMP_FILE_SIZE=UNLIMITED';
    EXECUTE IMMEDIATE 'ALTER SESSION SET TRACEFILE_IDENTIFIER=''ANVIL''';
    EXECUTE IMMEDIATE 'ALTER SESSION SET EVENTS ''10046 TRACE NAME CONTEXT FOREVER, LEVEL 12''';
  END IF;
EXCEPTION
WHEN OTHERS THEN
NULL;
END;
/
